//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class EventDispatcherWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(EventDispatcher), typeof(System.Object));
		L.RegFunction("Regist", Regist);
		L.RegFunction("UnRegist", UnRegist);
		L.RegFunction("DispatchEvent", DispatchEvent);
		L.RegFunction("ClearEvents", ClearEvents);
		L.RegFunction("New", _CreateEventDispatcher);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("instance", get_instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateEventDispatcher(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				EventDispatcher obj = new EventDispatcher();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: EventDispatcher.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Regist(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			EventDispatcher obj = (EventDispatcher)ToLua.CheckObject<EventDispatcher>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			MyEventHandler arg1 = (MyEventHandler)ToLua.CheckDelegate<MyEventHandler>(L, 3);
			obj.Regist(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegist(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			EventDispatcher obj = (EventDispatcher)ToLua.CheckObject<EventDispatcher>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			MyEventHandler arg1 = (MyEventHandler)ToLua.CheckDelegate<MyEventHandler>(L, 3);
			obj.UnRegist(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int DispatchEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			EventDispatcher obj = (EventDispatcher)ToLua.CheckObject<EventDispatcher>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			object[] arg1 = ToLua.ToParamsObject(L, 3, count - 2);
			obj.DispatchEvent(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearEvents(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			EventDispatcher obj = (EventDispatcher)ToLua.CheckObject<EventDispatcher>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.ClearEvents(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, EventDispatcher.instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

