///This code was generated by menu [Tools/sproto2cs], DO NOT EDIT!

public class c2s {
 public const string sproto = @"
.package {
	type 0 : integer
	session 1 : integer
}


sayhello 1 {
	request {
	  what 0 : string
	}
	response {
	  error_code 0 : integer
	  msg 1 : string
	}
}

login 2 {
	request {
		account 0 : string
		pwd 1 : string
	}
	response {
		error_code 0 : integer
	}
}

get 3 {
	request {
		what 0 : string
	}
	response {
		result 0 : string
	}
}

";
}