///This code was generated by menu [Tools/sproto2cs], DO NOT EDIT!

public class s2c {
 public const string sproto = @"
.package {
	type 0 : integer
	session 1 : integer
}


login 2 {
	request {
		account 0 : string
		pwd 1 : string
	}
	response {
		error_code 0 : integer
	}
}



heartbeat 99 {}

";
}